apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: sprinthive-kyc-bureau
    version: v1
  name: sprinthive-kyc-bureau-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sprinthive-kyc-bureau
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: sprinthive-kyc-bureau
        version: v1
    spec:
      containers:
      - image: gcr.io/jons-world/github-sprinthive-sprinthive-kyc-bureau:d9276f14edcdc4bf999f88ddfb117d834dd5d93b
        imagePullPolicy: IfNotPresent
        name: sprinthive-kyc-bureau-v1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
